apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: dotnetlinux
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: dotnetlinux
    spec:
      containers:
      # adjust image repo to pull from your registry
        - image: "anubhavkul89/demodotnetcore"
          imagePullPolicy: Always
          name: dotnetlinux
          ports:
            - containerPort: 80
